name: Tests

on: [push]

jobs:
  LintAndTest:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v1
      - name: Setup Node Environment
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: |
          yarn
      - name: Create env file
        run: |
          touch .env
          echo SPORTSDATAIO_API_KEY =${{ secrets.SPORTSDATAIO_API_KEY }} >> .env
          echo SPORTSPAGEFEEDS_API_KEY =${{ secrets.SPORTSPAGEFEEDS_API_KEY }} >> .env
          echo SPORTSRADAR_API_KEY =${{ secrets.SPORTSRADAR_API_KEY }} >> .env
          echo SPORTSRADAR_ACCESS_LEVEL =${{ secrets.SPORTSRADAR_ACCESS_LEVEL }} >> .env
      - name: Lint
        run: yarn eslint .
      - name: Test
        run: yarn test
        env:
          CI: true
